name: Deploy to Cloud Run

env:
  SERVICE_NAME: nutriai-api
  PROJECT_ID: nutri-ai-463621
  DOCKER_IMAGE_URL: gcr.io/nutri-ai-463621/github.com/Nutri-AI-TCC/nutriai-api

on:
  push:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }} # Aqui o uso de ${{ env.PROJECT_ID }} está correto, pois está dentro de um "with" de um step.

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker 

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying service ${{ env.SERVICE_NAME }}..."
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region southamerica-east1 \ 
            --allow-unauthenticated